### ISSUE TITLE
Work in progress

### ISSUE THREAD

**Issue by captainspain** [captainspain/web-terminal#1]
Any bug fixes, refactoring or improvements are welcome.

**Comment by fajryhamzah** [comment]
Bugs in interface. If the output has some html or php tags, the interface will be broken. Fixed in PR #5

![screenshot from 2018-10-04 14-29-14](https://user-images.githubusercontent.com/4441324/46459626-a08e8b00-c7e3-11e8-8d5f-c9bdc2a63d97.png)

**Comment by victorhsanjos** [comment]
Hi, 

I would like to help with separating the HTML code from PHP. Using [Plates](http://platesphp.com/v3/).

:smiley:

**Comment by misantron** [comment]
Try to add some tests

**Comment by 8ivek** [comment]
Warning: chdir(): No such file or directory (errno 2) in D:\xampp\htdocs\web-terminal\src\WebTerminal\Terminal.php on line 104

#7

**Comment by minved** [comment]
Bug in \CaptainSpain\WebTerminal\Session::isEmpty() method - always returns true regardless of what session data contains.

PR #8

**Comment by captainspain** [comment]
Hi @victorhsanjos ,

Not sure if I would like a template engine. 
I was thinking to refactor it a bit. So it uses javascript fetch instead of doing POST requests.
When there is a bit more of data in `terminal.json` the screen flickers when you submit a command.
The javascript fetch would fix the flickers because it does not do a page refresh.
That way I could place the html inside the `index.php`, because there is almost no html..

So I don't think we need a template engine.

**Comment by victorhsanjos** [comment]
> Hi @victorhsanjos ,
> 
> Not sure if I would like a template engine.
> I was thinking to refactor it a bit. So it uses javascript fetch instead of doing POST requests.
> When there is a bit more of data in `terminal.json` the screen flickers when you submit a command.
> The javascript fetch would fix the flickers because it does not do a page refresh.
> That way I could place the html inside the `index.php`, because there is almost no html..
> 
> So I don't think we need a template engine.

I thought we used a template system to create new themes.

**Comment by captainspain** [comment]
That was my idea as well. But how would you fix the screen flickers? @victorhsanjos

**Comment by victorhsanjos** [comment]
> That was my idea as well. But how would you fix the screen flickers? @victorhsanjos

We could open another issue to fix the screen flickers.

**Comment by captainspain** [comment]
@victorhsanjos I have already made an example.
You can check it in branch [change-post-to-xhr-requests](https://github.com/captainspain/web-terminal/tree/change-post-to-xhr-requests).
It does not work properly but this way you can still customize it by adding your own css file. Every `<span>` has it's own class.
Maybe to build something nice in javascript so it can be extended. that way it is fully custom I think.

**Comment by misantron** [comment]
> 
> 
> Try to add some tests

#10 ready for review
